version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@1.1.0

jobs:
  build:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test --coverage
      - run:
          name: Upload coverage report
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - build:
          requires:
            - node/test
