version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - run:
          name: Install dependencies and run tests in backend directory
          command: |
            cd /home/circleci/project/backend/
            npm install
            npm run test
      - run:
          name: Run Jest tests
          command: |
            npm install --save-dev jest
            npm test
