version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

orbs:
  codecov: codecov/codecov@3.2.4
