version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  build_test_and_deploy:
    jobs:
      - node/test:
          version: 14.17.3
      - node/build:
          version: 14.17.3
          requires:
            - node/test
      - node/deploy:
          requires:
            - node/build
          filters:
            branches:
              only: main
