version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

  upload-coverage:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Upload coverage reports to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - upload-coverage:
          requires:
            - build
          filters:
            branches:
              only:
                - main
