version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - run:
          name: Change to project directory
          command: cd /home/circleci/project/backend/
      - run:
          name: List files in project directory
          command: ls /home/circleci/project/
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
